version: "3.9"


services:


  postgres_db:

    image: postgres:15.2

    environment:
      POSTGRES_DB: "parser"
      POSTGRES_USER: "userIra"
      POSTGRES_PASSWORD: "1111"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U userIra -d parser" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
        resources:
          limits:
            cpus: '1'
            memory: 4G


  redis:
    image: redis:6.0

  celery:
    build: .
    image: celery:4
    command: celery -A myproject worker -l info
    volumes:
      - .:/app
    depends_on:
      - postgres_db
      - redis

  scrapping-init:
    build: .
    image: parser:v0.1
    environment:
      DJANGO_SUPERUSER_EMAIL: djangoProjectUser@yandex.ru
      DJANGO_SUPERUSER_NAME: ira
      DJANGO_SUPERUSER_PASSWORD: 1111

    command: python manage.py migrate && python manage.py createsuperuser --noinput
    depends_on:
      postgres_db:
        condition: service_healthy

  django-parser:
    image: parser:v0.1
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure

    environment:
      DJANGO_DEBUG: 1
      DJANGO_SECRET_KEY: django-insecure-%5@s2h&zm7&v7#5r#7!vjvf@r0n7g7h1u-m)l#p)!8kc2(&pct

    ports:
      - "8080:8000"

#    volumes:
#      - ",/static:/app/static:ro"

    depends_on:
      - postgres_db